# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.runs/synth_1/Top_module.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.cache/wt [current_project]
set_property parent.project_path D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo d:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/cpu/program.mem
read_verilog -library xil_defaultlib -sv {
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/apb/APB_master_compat.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/GPIO_peri/GPI.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/GPIO_peri/GPIO.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/GPIO_peri/GPO.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/apb/Top_APB.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/cpu/Top_CPU.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/cpu/Top_Memory.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/cpu/Top_Memory_CNTL.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/cpu/alu.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/apb/apb_mmio_bridge.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/apb/apb_regs.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/cpu/branch_cmp.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/cpu/control.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/cpu/data_memory.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/cpu/datapath.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/GPIO_peri/gpi_apb_wrapper.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/GPIO_peri/gpio_apb_wrapper.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/GPIO_peri/gpo_apb_wrapper.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/cpu/imm_extender.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/cpu/pc_reg.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/cpu/reg_n.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/cpu/register_file.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/cpu/rom_table.sv
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/Top_module.sv
}
read_verilog -library xil_defaultlib {
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/uart_peri/fifo/Top_FIFO.v
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/uart_peri/uart_source/Top_UART.v
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/uart_peri/uart_source/baud_tick_16oversample.v
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/uart_peri/fifo/fifo_control.v
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/uart_peri/fifo/fifo_register.v
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/uart_peri/uart_source/rx.v
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/uart_peri/uart_source/tx.v
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/uart_peri/uart_apb_wrapper.v
  D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/sources_1/uart_peri/uart_core.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/constrs_1/Basys-3-Master.xdc
set_property used_in_implementation false [get_files D:/verilog_Ai_ondevice/In_progress/RISC-V_Multi_Cycle/RISC-V_Multi_Cycle.srcs/constrs_1/Basys-3-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Top_module -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_module.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_module_utilization_synth.rpt -pb Top_module_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
